### ISSUE TITLE
Open the neovim-cn organization for the China user!

### ISSUE THREAD

**Issue by wsdjeg** [Neovim-cn/Neovim-cn.gitgub.io#1]
@tarruda @ZyX-I @elmart @justinmk @mhinz
I am start to create a new ORG for chinese user,and most of my friend use vim instead of neovim ,I hope they can change to neovim ,also I want to translate  [vim-galore](https://github.com/mhinz/vim-galore) into chinese.or maybe a Readme_zh_CN.md can be added into the origin repo.

**Comment by mhinz** [comment]
:+1:

**Comment by ZyX-I** [comment]
AFAIR github allowed using team mentions like @neovim/core. Only from https://github.com/neovim repositories?

**Comment by wsdjeg** [comment]
@ZyX-I Sorry for my pool english ,I can not understand what you are meanning.

**Comment by ZyX-I** [comment]
@wsdjeg Normally (at least, I have seen this in some Neovim issue) instead of listing 100500 people like you did you may list one team: @neovim/core (https://github.com/blog/1121-introducing-team-mentions). But I do not see this working in this issue.

**Comment by wsdjeg** [comment]
I know ,I have tried with this,but it does not work ,only works in https://github.com/neovim/neovim
EDIT : sorry still doed not work in https://github.com/neovim/neovim

**Comment by tarruda** [comment]
@wsdjeg great to see chinese org for Neovim. Can you send a PR with `Readme_zh_CN.md`?

**Comment by wsdjeg** [comment]
@tarruda I am now working on it,but as  vim-galore is changed everyday,so I need some times to finished it.

**Comment by wsdjeg** [comment]
I hava fork neovim into this org,should I translate the readme of neovim ,and send this PR?

**Comment by wsdjeg** [comment]
@ZyX-I I think this feature should be used like this, `@org_name/team_name`
